### ISSUE TITLE
Mass tagging and commenting only possible if you start selection with the first item in the list

### ISSUE THREAD

**Issue by dejanpan** [ternaris/marv-robotics#1]
In not, the tag and comment options don't become active. 

See: 
<img width="1255" alt="screen shot 2016-10-09 at 6 06 12 am" src="https://cloud.githubusercontent.com/assets/17376/19215932/be1a66a0-8de6-11e6-9ef2-57019e255e20.png">

![Uploading Screen Shot 2016-10-09 at 6.08.43 AM.png…]()

**Comment by chaoflow** [comment]
Fixed with https://github.com/ternaris/marv/commit/9e271b58b3673a1946b7d5c753511744051f420a

**Comment by NikolausDemmel** [comment]
Works for me. Thanks!
