### ISSUE TITLE
marv fileset discard does not remove discarded filesets from web interface

### ISSUE THREAD

**Issue by jpsamper2009** [ternaris/marv-robotics#14]
I have a given fileset that has been scanned (i.e. marv fileset scan), and it is listed on the overview page. Then, I run marv fileset discard <uuid>  and after refreshing the page, the overview still shows the link, but it is broken. I have found that restarting the uwsgi will update the overview page properly, but this is not ideal.

**Comment by NikolausDemmel** [comment]
I believe this is a known issue, fixed in the current enterprise edition. Not sure when the next community edition update is planned @chaoflow?

**Comment by chaoflow** [comment]
Fixed in 17.11 now also for CE.
