### ISSUE TITLE
Improve CLI for working with datasets (removing datasets, running nodes, ...)

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics#3]
I am in the situation that I added some bags that I now want to ignore with `.marvignore`. So for it is only possible to remove them if you know the uuid. It would be great if the cli would support some workflow for finding the current filesets. 

Ideas:

```
$ marv fileset list
./scanroot/foo-bar <uuid>
./scanroot/quux-quax <uuid>
...
```

```
$ marv  fileset discard `marv fileset list scanroot/subfolder/ --uuid`
```

```
$ marv fileset discard --ignored
```

**Update:**

In general (not just for removing filesets, but also e.g. for re-running nodes on a subset of filesets) it would be great of the CLI offered a similar power to select filesets as does the HTTP api. I don't know about a suitable syntax, but something like the following would be very helpful:

```
$ marv fileset list --added-since 2016-10-01

$ marv fileset list --filter "bag.start_time >=  2016-10-01"

$ marv node run --node my-updated-node --filter-filesets "bag.start_time >=  2016-10-01 and bag.name ~= '.*gps.*'"
```

I'm changing the title to something more general.

**Comment by NikolausDemmel** [comment]
This is related also to #9, for which one also needs a way to select a subset of bagfiles for which to rerun a set of changed nodes.

**Comment by chaoflow** [comment]
@NikolausDemmel to remove datasets in specific directories:

```
marv query --path path/to/ignored/directory |xargs marv discard
```

Regarding your Update, I'll create a new issue.
