### ISSUE TITLE
Feature requests: multiple scan roots

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics#4]
Does the architecture allow to have multiple scanroots, or is there some part in the system that assumes that filesets are located relative to some common root?

It is not super high priority, but I think it would make sense and it would be convenient to allow to configure a list of scanroots instead of just one. You can probably do the same with symlinks or bindmounts in many situations, but native support would be great. I'm assuming here that it would not be much effort and thus low hanging fruit.

**Comment by chaoflow** [comment]
Multiple [scanroots](https://ternaris.com/marv-robotics/docs/config.html#scanroots) are now supported in EE and CE.
