### ISSUE TITLE
beta install instructions

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics#5]
Unlike what the wiki said, I needed

```
pip install --pre marv-robotics
```

For people not familiar with `pip`, this might be quite deterring, since the immediate error message does not tell you what is wrong. Only if you look into the mentioned log file does it say that you could try `--pre`.

**Comment by chaoflow** [comment]
Thanks a lot! Instructions are updated: https://github.com/ternaris/marv-robotics/commit/79d912612eefb3e6f92b8beba15f0023dd3a0aa7
