### ISSUE TITLE
Workflow for rerunning jobs

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics#9]
I was under the impression that jobs were supposed to rerun with changed mtime. This does not seem to be the case in 2.0.0b2. Is that intended behaviour?

What is the suggested workflow for rerunning jobs when either:

1. the data has changed (e.g. rosbag migration), or
2. some jobs have changed (job development)?

**Comment by chaoflow** [comment]
Currently in both cases you need to to rerun manually by setting the ``--rerun`` flag.

For case 1, this should happen automatically and will be fixed for 2.0.0b3

**Comment by NikolausDemmel** [comment]
Thanks! I'll close this.
